
set(ENABLED_GEMS
    Planet_Storm
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    PhysXDebug
    PhysXSamples
    PythonAssetBuilder
    QtForPython
    ScriptCanvas
    ScriptCanvasDeveloperGem
    ScriptCanvasTesting
    Vegetation
    GameStateSamples
    ScriptedEntityTweener
)
